runner and detection
fred3m/scarlet_extensions pull request #4
Opened 2020-09-04 21:26 UTC by herjy

This PR contains my original detection code, though I think @fred3m has a better, more modular one now that I haven't seen in the code. I also added a Runner class that runs scarlet with simplified input.

2020-09-07 13:13 UTC, fred3m requested changes
This looks good overall, I just have a few minor changes requested in the PR comments. In addition, I don't think that "Run" is the best name for the location for the runner. At the very least it should be "run" (lower case) but perhaps it would be better to call it "scripts" so that it's clear that it contains scripts that are meant to be executable in python.

2020-09-07 13:13 UTC, fred3m commented on scarlet_extensions/Run/runner.py
> +        self.pixels = np.stack((catalog['y'], catalog['x']), axis=1)
may `self.pixels` -> `self.pixel_coords`?

2020-09-07 13:13 UTC, fred3m commented on scarlet_extensions/Run/runner.py
> +    def __init__(self, datas, model_psf, ra_dec = None):
`datas` -> `data`? That makes more sense and is the same as the private variable that you assign to it in the init.

2020-09-07 13:13 UTC, fred3m commented on scarlet_extensions/Run/runner.py
> +            the list of Data objects to run scarlet on
You might want to make it clear what the expected format of the data object is, eg. that it's a compressed numpy file with keys (`images` = 3D image cube, etc).

2020-09-07 13:13 UTC, fred3m commented on scarlet_extensions/initialization/detection.py
> +        self.wcss = wcs
one `s` in `wcss`. This just looks confusing.

2020-09-07 13:13 UTC, fred3m commented
Once you've merged this PR I'll push my changes to the detection algorithm and ask you to review that.

2020-09-08 15:11 UTC, herjy commented
Changes pushed.

2020-09-08 15:23 UTC, fred3m approved these changes

2020-09-08 15:23 UTC, fred3m commented
Great, thanks Remy. Feel free to merge.

2020-09-08 15:30 UTC, merged